version: '3'

services:
  monolitico:
    build: ./monolitico
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    depends_on:
      - mongo
  usuarios:
    build: ./microservicios/usuarios
    depends_on:
      - mongo
  mongo:
    image: mongo
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - monolitico
      - frontend
      - usuarios
  